/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartsIndexRouteImport } from './routes/parts.index'
import { Route as PartsMotorControllerRouteImport } from './routes/parts.motor-controller'
import { Route as PartsGpsLoggerRouteImport } from './routes/parts.gps-logger'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsIndexRoute = PartsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartsRoute,
} as any)
const PartsMotorControllerRoute = PartsMotorControllerRouteImport.update({
  id: '/motor-controller',
  path: '/motor-controller',
  getParentRoute: () => PartsRoute,
} as any)
const PartsGpsLoggerRoute = PartsGpsLoggerRouteImport.update({
  id: '/gps-logger',
  path: '/gps-logger',
  getParentRoute: () => PartsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/parts': typeof PartsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parts/gps-logger': typeof PartsGpsLoggerRoute
  '/parts/motor-controller': typeof PartsMotorControllerRoute
  '/parts/': typeof PartsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parts/gps-logger': typeof PartsGpsLoggerRoute
  '/parts/motor-controller': typeof PartsMotorControllerRoute
  '/parts': typeof PartsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/parts': typeof PartsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/parts/gps-logger': typeof PartsGpsLoggerRoute
  '/parts/motor-controller': typeof PartsMotorControllerRoute
  '/parts/': typeof PartsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/parts'
    | '/sitemap.xml'
    | '/parts/gps-logger'
    | '/parts/motor-controller'
    | '/parts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/sitemap.xml'
    | '/parts/gps-logger'
    | '/parts/motor-controller'
    | '/parts'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/parts'
    | '/sitemap.xml'
    | '/parts/gps-logger'
    | '/parts/motor-controller'
    | '/parts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PartsRoute: typeof PartsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts/': {
      id: '/parts/'
      path: '/'
      fullPath: '/parts/'
      preLoaderRoute: typeof PartsIndexRouteImport
      parentRoute: typeof PartsRoute
    }
    '/parts/motor-controller': {
      id: '/parts/motor-controller'
      path: '/motor-controller'
      fullPath: '/parts/motor-controller'
      preLoaderRoute: typeof PartsMotorControllerRouteImport
      parentRoute: typeof PartsRoute
    }
    '/parts/gps-logger': {
      id: '/parts/gps-logger'
      path: '/gps-logger'
      fullPath: '/parts/gps-logger'
      preLoaderRoute: typeof PartsGpsLoggerRouteImport
      parentRoute: typeof PartsRoute
    }
  }
}

interface PartsRouteChildren {
  PartsGpsLoggerRoute: typeof PartsGpsLoggerRoute
  PartsMotorControllerRoute: typeof PartsMotorControllerRoute
  PartsIndexRoute: typeof PartsIndexRoute
}

const PartsRouteChildren: PartsRouteChildren = {
  PartsGpsLoggerRoute: PartsGpsLoggerRoute,
  PartsMotorControllerRoute: PartsMotorControllerRoute,
  PartsIndexRoute: PartsIndexRoute,
}

const PartsRouteWithChildren = PartsRoute._addFileChildren(PartsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PartsRoute: PartsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
